/* tslint:disable */
/* eslint-disable */
/**
 * Légifrance
 *  Afin de faciliter la réutilisation des données juridiques, la DILA met à disposition du public une API de Légifrance. Ce document a pour objectif de décrire les méthodes de l\'API Légifrance, présentées à l\'aide du framework Swagger. Vous pouvez également télécharger une [documentation complémentaire](https://www.legifrance.gouv.fr/contenu/Media/Files/pied-de-page/description-des-tris-et-filtres-de-l-api.xlsx) ainsi que des [exemples d’utilisation](https://www.legifrance.gouv.fr/contenu/Media/Files/pied-de-page/exemples-d-utilisation-de-l-api.docx) de l\'API.  Cet accès vous permet d’expérimenter l\'API sur un environnement de test et de vous familiariser avec les différentes méthodes.  À noter : - L\'environnement de test peut être indisponible. - Les appels sont limités par quotas.  Les mises à jour correctives et évolutives sont réalisées dans un premier temps sur cet environnement. L\'API mise à disposition correspond à celle utilisée par le site de Légifrance.  Les données ne sont pas identiques à celles de Production.  L\'API Légifrance est mise à disposition sous [conditions](https://www.legifrance.gouv.fr/contenu/pied-de-page/open-data-et-api).  Pour toute question, vous pouvez écrire à l\'adresse retours-legifrance-modernise@dila.gouv.fr.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: retours-legifrance-modernise@dila.gouv.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "https://sandbox-api.piste.gouv.fr/dila/legifrance/lf-engine-app".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: AxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}
