/* tslint:disable */
/* eslint-disable */
/**
 * Légifrance
 *  Afin de faciliter la réutilisation des données juridiques, la DILA met à disposition du public une API de Légifrance. Ce document a pour objectif de décrire les méthodes de l\'API Légifrance, présentées à l\'aide du framework Swagger. Vous pouvez également télécharger une [documentation complémentaire](https://www.legifrance.gouv.fr/contenu/Media/Files/pied-de-page/description-des-tris-et-filtres-de-l-api.xlsx) ainsi que des [exemples d’utilisation](https://www.legifrance.gouv.fr/contenu/Media/Files/pied-de-page/exemples-d-utilisation-de-l-api.docx) de l\'API.  Cet accès vous permet d’expérimenter l\'API sur un environnement de test et de vous familiariser avec les différentes méthodes.  À noter : - L\'environnement de test peut être indisponible. - Les appels sont limités par quotas.  Les mises à jour correctives et évolutives sont réalisées dans un premier temps sur cet environnement. L\'API mise à disposition correspond à celle utilisée par le site de Légifrance.  Les données ne sont pas identiques à celles de Production.  L\'API Légifrance est mise à disposition sous [conditions](https://www.legifrance.gouv.fr/contenu/pied-de-page/open-data-et-api).  Pour toute question, vous pouvez écrire à l\'adresse retours-legifrance-modernise@dila.gouv.fr.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: retours-legifrance-modernise@dila.gouv.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

